### PR TITLE
Fixes web view

### PR DESCRIPTION
**Pull request by benshippee**

### CODE REVIEW

**Comment by cryo28** [comment]
@benshippee  Could you please describe this change?

**Comment by benshippee** [comment]
The change from `-%>` to `%>` solves template rendering errors when navigating to the status page for sidekiq.  Attempting to navigate to the page without this patch results in the following for me:

`/var/www/cg_api/shared/bundle/ruby/2.2.0/bundler/gems/sidekiq_status-6e33e4a6bd4f/lib/sidekiq_status/web.rb:54: syntax error, unexpected ';' ...statuses.each do |container| -; @_out_buf.concat "\n" ... ^ /var/www/cg_api/shared/bundle/ruby/2.2.0/bundler/gems/sidekiq_status-6e33e4a6bd4f/lib/sidekiq_status/web.rb:73: syntax error, unexpected ';' ... "; if container.killable? -; @_out_buf.concat "\n" ... ^ /var/www/cg_api/shared/bundle/ruby/2.2.0/bundler/gems/sidekiq_status-6e33e4a6bd4f/lib/sidekiq_status/web.rb:75: syntax error, unexpected keyword_elsif, expecting keyword_end ...t_buf.concat " "; elsif container.kill_requested? -;... ... ^ /var/www/cg_api/shared/bundle/ruby/2.2.0/bundler/gems/sidekiq_status-6e33e4a6bd4f/lib/sidekiq_status/web.rb:75: syntax error, unexpected ';' ...if container.kill_requested? -; @_out_buf.concat "\n" ... ^ /var/www/cg_api/shared/bundle/ruby/2.2.0/bundler/gems/sidekiq_status-6e33e4a6bd4f/lib/sidekiq_status/web.rb:80: syntax error, unexpected ';' ; @_out_buf.concat " "; end -; @_out_buf.concat "\n" ^ /var/www/cg_api/shared/bundle/ruby/2.2.0/bundler/gems/sidekiq_status-6e33e4a6bd4f/lib/sidekiq_status/web.rb:81: syntax error, unexpected ';' ; @_out_buf.concat " "; if @statuses.empty? -; @_out_buf.concat "\n" ^ /var/www/cg_api/shared/bundle/ruby/2.2.0/bundler/gems/sidekiq_status-6e33e4a6bd4f/lib/sidekiq_status/web.rb:85: syntax error, unexpected ';' ; @_out_buf.concat " "; end -; @_out_buf.concat "\n" ^ /var/www/cg_api/shared/bundle/ruby/2.2.0/bundler/gems/sidekiq_status-6e33e4a6bd4f/lib/sidekiq_status/web.rb:96: syntax error, unexpected keyword_end, expecting end-of-input end;end;end;end ^`

From the above error and resulting stack trace it is due to the `-%>` instances in the template.

**Comment by cryo28** [comment]
Well, this is weird. "-" and before ERB closing tags is a signal for ERB working in trim mode to strip empty line from the output. And I don't have this error on vanilla sinatra and sidekiq. I wonder if you somehow disabled ERB trim mode?

**Comment by benshippee** [comment]
Ah, upon further inspection it looks like this gem:
https://github.com/davydovanton/sidekiq-statistic
 changes the defaults for the trim mode.

**Comment by cryo28** [comment]
Got you. Anyway I think I would not hurt to remove this trim modifiers. SidekiqStatus::Web

**Pull request merged**
